library("RSelenium")
startServer()
checkForServer()
remDr <- remoteDriver()
remDr$open()
remDr$navigate("https://www.google.com/maps/place/Hospet")
Sys.sleep(5)
webElem <- remDr$findElement(using = 'class', "searchbox-searchbutton-container")
webElem$clickElement()
webElem$sendKeysToElement(list("R Cran", key = "enter"))